ports:
  - port: 5000
    onOpen: open-browser

tasks:
- command: git status && git pull
- command: |
    virtualenv -p python3 venv &&
    source venv/bin/activate &&
    pip install -r requirements.txt &&
    FLASK_APP=metrics-api.py flask run --host 0.0.0.0
- command: |
    npm install --prefix frontend &&
    npm run-script build

