ports:
  - port: 5000
    onOpen: open-browser

tasks:
- command: |
    virtualenv -p python3 venv &&
    source venv/bin/activate &&
    pip install -r requirements.txt &&
    cd frontend &&
    npm install &&
    yarn build &&
    cd .. &&
    FLASK_APP=metrics-api.py flask run --host 0.0.0.0
- command: git status && git pull
