version: "3.7"
services:
  flask:
    container_name: metrics-flask
    build:
      dockerfile: Dockerfile
      target: flask-dev
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
  react:
    container_name: metrics-react
    build:
      context: .
      dockerfile: Dockerfile
      target: react-dev
    volumes:
      - ./frontend/build:/app/frontend/build
      - ./frontend/public:/app/frontend/public
      - ./frontend/src:/app/frontend/src
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      REACT_APP_METRICS_BASE_URL: http://localhost:5000
      CHOKIDAR_USEPOLLING: "true"